//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Name X.
        /// </summary>
        public static string AxisNameX {
            get {
                return ResourceManager.GetString("AxisNameX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Name Y.
        /// </summary>
        public static string AxisNameY {
            get {
                return ResourceManager.GetString("AxisNameY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcValue.
        /// </summary>
        public static string CalcValue {
            get {
                return ResourceManager.GetString("CalcValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH1.
        /// </summary>
        public static string CH1 {
            get {
                return ResourceManager.GetString("CH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH10.
        /// </summary>
        public static string CH10 {
            get {
                return ResourceManager.GetString("CH10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH2.
        /// </summary>
        public static string CH2 {
            get {
                return ResourceManager.GetString("CH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH3.
        /// </summary>
        public static string CH3 {
            get {
                return ResourceManager.GetString("CH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH4.
        /// </summary>
        public static string CH4 {
            get {
                return ResourceManager.GetString("CH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH5.
        /// </summary>
        public static string CH5 {
            get {
                return ResourceManager.GetString("CH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH6.
        /// </summary>
        public static string CH6 {
            get {
                return ResourceManager.GetString("CH6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH7.
        /// </summary>
        public static string CH7 {
            get {
                return ResourceManager.GetString("CH7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH8.
        /// </summary>
        public static string CH8 {
            get {
                return ResourceManager.GetString("CH8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH9.
        /// </summary>
        public static string CH9 {
            get {
                return ResourceManager.GetString("CH9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string ChannelNameCombo {
            get {
                return ResourceManager.GetString("ChannelNameCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPerLoop.
        /// </summary>
        public static string DataPerLoop {
            get {
                return ResourceManager.GetString("DataPerLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string GraphNameCombo {
            get {
                return ResourceManager.GetString("GraphNameCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string LabelChannel {
            get {
                return ResourceManager.GetString("LabelChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineSize.
        /// </summary>
        public static string LineSize {
            get {
                return ResourceManager.GetString("LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form1.
        /// </summary>
        public static string MainFormName {
            get {
                return ResourceManager.GetString("MainFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Channel.
        /// </summary>
        public static string MaxCH {
            get {
                return ResourceManager.GetString("MaxCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLoop.
        /// </summary>
        public static string MaxLoop {
            get {
                return ResourceManager.GetString("MaxLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxPlot.
        /// </summary>
        public static string MaxPlot {
            get {
                return ResourceManager.GetString("MaxPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max Y.
        /// </summary>
        public static string MinMaxY {
            get {
                return ResourceManager.GetString("MinMaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ModeNameCombo {
            get {
                return ResourceManager.GetString("ModeNameCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot Count.
        /// </summary>
        public static string ShotCount {
            get {
                return ResourceManager.GetString("ShotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulateData.
        /// </summary>
        public static string SimulateData {
            get {
                return ResourceManager.GetString("SimulateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartValue.
        /// </summary>
        public static string StatValue {
            get {
                return ResourceManager.GetString("StatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ms].
        /// </summary>
        public static string TimeUnit {
            get {
                return ResourceManager.GetString("TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string UpdateAll {
            get {
                return ResourceManager.GetString("UpdateAll", resourceCulture);
            }
        }
    }
}
